name: Deploy Next.js App

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Crear archivo .env
        run: |
          cat <<EOF > .env
          NEXT_PUBLIC_GOOGLE_MAP_API_KEY=https://maps.googleapis.com/maps/api/js?v=3.exp&key=YOUR_GOOGLE_API_KEY&libraries=geometry,drawing,places
          NEXT_PUBLIC_FIREBASE_API_KEY=AIzaSyB5mQQx8K-9nhlMKFKVXLo-z0CLQgDJygY
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=renta-motos-backend-f471c.firebaseapp.com
          NEXT_PUBLIC_FIREBASE_PROJECT_ID=renta-motos-backend-f471c
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=renta-motos-backend-f471c.appspot.com
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=733923924954
          NEXT_PUBLIC_FIREBASE_APP_ID=1:733923924954:web:6ac565f0af6d8338523ee3
          FIREBASE_TYPE=service_account
          FIREBASE_PROJECT_ID=renta-motos-backend-f471c
          FIREBASE_PRIVATE_KEY_ID=2fd1f7c3e8bd3f541ff843c99b838cd6f91b7225
          FIREBASE_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDp08pdV6MfXvXz\n8tyRtCt9+a2ajQK5UKOAxWmyccI0iRkfW/Ij3g9loUJlUV+Iaglfb0/1BbRu/8HZ\nPjpVeB6Iyc0dz44e2a7JQaG9iLDq8Zgz6u2nyWvH+zWdD88Z0BhRtzVAMQccM1eN\nWRnDaQdwYBILRUxyhlPAYKxhXQZPaJ/mQn573vCTkdj2fWa2YNPQn0Xbih2KLxrv\nHJ5JnSIbbbag4Un97+04Sd6iP69EA+Y7biYbuHlttdUl2w1WSeLaZubf55eq2VS4\nuKyjmXLihAkz2+nbAYmZp81ZQxXYl6Z0ILP9JdANVMcV1iSHSZyXwLMnKZT2ltTn\nMg+HyyW3AgMBAAECggEAC4F6ljWUlxvBnNjo+0RzKsDpRs8Z1guT7WdevZifwUez\nvu7JJJ8DK/GPm6kG5eat17ku+olm07AYa6ZbvCPr1g2etGZSVyNIA1WMQ2V2qyuV\n3TbPWJpuiB8iMrx56N/BVUK0x0KtAmQRB/6ykq0tirKM1hV5Xwiha2MhEwNppujm\nIH/wudYkGDjbPj6L8Z47emFt2H5/c+um/R2UHCcXLt9SWFZBp5byuPZXJNMro+ZF\nBB+Zs+raLZrHANikfHf8bZMCYFMxNNGHreIjazNe88MtLShOjIP030ihuUVFlFQO\nXnyk6558LLZ9GGmG0cvg3rp//OW+l4l5Td4PBdimgQKBgQD7OIR+9MfqCpDcgcFJ\nk9pyWjS2lsRH2EEpbTKnsV9Z99HHlWgcK+D8G0AuKOWaNT7DtOoK+rdF4DdnpfQ/\nHRnZJN1raFKWoVcWZiNxI/MYDiFzXwvlXgzhn0QXwv8FNBSEVtYM3O8PiYt7cV1o\nbGFa95jtg9hAwNu7gQ1KjgPyNwKBgQDuRpBtVVptj1hgngf6CLlxg/+O/zSG0gFm\nUBu+3K5LjIchksZ1vctILaMoFEwxXaHGqQaMLvjOOPd6zMKX47ThxjMM4pzViK0j\nLh7Y0u1TPOWnLTidr9BcM0SM79ncd1hh74n4CXAtHAuEVJoH+9bU4zf5wvyWYWnL\n07e0YPaogQKBgDSlZW7NkU+Eo1LyhjULHQ41xTI2ai+8K/uofKMT0q2h935h2w18\nTIvIkiyaOXOVkO+mbB2c6Odl03aPGp5XVOFijlxB4nzalsuE4AyHwhvaajwpQO7y\nRLTLkZOBM7w9a8dIA1dyvU5+PpLB8Rc/Dy/nD09G//yh7epfYw+qrz0FAoGBAJ6K\nSRLWVeLMHAu9WqVdJLaJE4O7/uEt3kyLRMrL3xTZnhgSpwY0kIuoAgVq6/90w22B\njZ+8qUPd15zXnSqfEf2feNw79AqIdFsSFuhCADMAM/X2OtOA5exTGGuGM7ljl2Ui\nkvR8oy0AmhEkkZB6WskvnlELEjGlA1XhuzvDwJsBAoGBAMsngLFAXH7tvdAXeKzi\nBhyWA8rcqQPpYcxdB9ssumhKW+IEr27+6zGU2J6Nc+jgNlFQ+CUuL0K1QqluqHKW\nqJhzkKYKjvngxORmsLa37oQqqEm51Hdkx/mJVNVoCQlFLFEJd4tJC9I643NG6Uv5\n2Mvyo/Lws3LEDcMqpG9XMiFI
          NEXT_PUBLIC_URL_API_SERVER=https://renta-motos-backend.vercel.app/api
          NEXT_PUBLIC_PAYPAL_OAUTH_URL=https://api.paypal.com/v1/oauth2/token
          NEXT_PUBLIC_PAYPAL_ORDERS_URL=https://api.paypal.com/v2/checkout/orders
          NEXT_PUBLIC_PAYPAL_CLIENT_ID=ATa78xZLRHPjMrRrx1ixF4oOxP37VZZ4kkS9SPQE82QZGicibKqZ5klYhYvJ6mKaLBC8grJC12zh4_PF
          PAYPAL_SECRET=EMydtQ7BuCwrOunuqRWXC9WE-n5ux_vm8nYeUDKGsrD76R3y26pTQzEtvD3sOteC7A8PsgG_-k0apTrb
          EOF

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy to VPS with Password
        env:
          HOST: 195.179.193.101
          USERNAME: root
          PASSWORD: q2*L7QPhOX]6g>cc]oP4
          REMOTE_DIR: "/path/to/your/app"  
        run: |
          sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "mkdir -p $REMOTE_DIR"
          sshpass -p "$PASSWORD" rsync -avz --exclude='node_modules' ./ $USERNAME@$HOST:$REMOTE_DIR
          sshpass -p "$PASSWORD" ssh $USERNAME@$HOST "cd $REMOTE_DIR && npm install --production && pm2 restart app-name || pm2 start npm --name app-name -- start"
